### ISSUE TITLE
elemento img - corrigir id

### ISSUE THREAD

**Issue by luizfilho46** [SimoneLopes1416/dr-norman#1]
img id="img-div" src="img/homens.no.campo.jpg"

o id deve ter o valor "image"

**Comment by luizfilho46** [comment]
id="tribute-info" - section: 

O conteúdo da página deve estar dentro desse elemento. Atualmente, ele está vazio

**Comment by SimoneLopes1416** [comment]
Done

**Comment by luizzfilho** [comment]
Solução atende!
Grato!
